Repository woowa-techcamp-2020/todo-7, pull requests merged in 2020-07, with the labels that each got.

#1 docs: 이슈 & PR 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#13 feat: 반응형 레이아웃 구현 #9
  client/index.html
  client/main.js
  client/reset.css
  client/styles.css
Labels: frontend, ui

#14 feat: 백엔드 환경설정하기
  .gitignore
  server/app.js
  server/bin/www
  server/models/index.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/views/error.pug
  server/views/index.pug
  server/views/layout.pug
Labels: architecture, backend, database

#17 feat: 데이터베이스 클래스화, 라우터와 컨트롤러 구조 설정 #15
  server/app.js
  server/bin/www.js
  server/controllers/events.js
  server/controllers/groups.js
  server/controllers/notes.js
  server/controllers/projects.js
  server/controllers/users.js
  server/models/events.js
  server/models/groups.js
  server/models/index.js
  server/models/model.js
  server/models/notes.js
  server/models/projects.js
  server/models/users.js
  server/package-lock.json
  server/package.json
  server/routes/events.js
  server/routes/groups.js
  server/routes/index.js
  server/routes/notes.js
  server/routes/projects.js
  server/routes/users.js
  server/utils/auth.js
  server/utils/helper.js
Labels: api, architecture, backend, database

#21 feat: 프론트엔드 구조 설계 및 기본 레이아웃 구현
  client/dist/index.html
  client/dist/main.css
  client/dist/main.js
  client/src/components/element.js
  client/src/components/molecules/event.js
  client/src/components/molecules/noteCard.js
  client/src/components/molecules/noteColumnHeader.js
  client/src/components/molecules/pageHeader.js
  client/src/components/organisms/noteColumn.js
  client/src/components/organisms/noteColumns.js
  client/src/components/pages/home.js
  client/src/components/pages/login.js
  client/src/components/templates/template.css
  client/src/index.html
  client/src/main.js
  client/src/reset.css
  client/src/styles.css
Labels: architecture, frontend, ui

#30 docs: api 문서 추가
  README.md
  docs/api.md
Labels: api, document

#25 feat: Project page를 컴포넌트 모듈을 사용하여 MVC 구조로 구현하기
  client/dist/index.html
  client/dist/main.css
  client/dist/main.js
  client/src/apis/index.js
  client/src/apis/project.js
  client/src/apis/user.js
  client/src/components/atoms/button/index.js
  client/src/components/atoms/button/styles.css
  client/src/components/atoms/counter/index.js
  client/src/components/atoms/counter/styles.css
  client/src/components/atoms/icon/index.js
  client/src/components/atoms/icon/styles.css
  client/src/components/atoms/textarea/index.js
  client/src/components/atoms/textarea/styles.css
  client/src/components/element.js
  client/src/components/molecules/card/index.js
  client/src/components/molecules/card/styles.css
  client/src/components/molecules/columnHeader/index.js
  client/src/components/molecules/columnHeader/styles.css
  client/src/components/molecules/event.js
  client/src/components/molecules/noteCard.js
  client/src/components/molecules/noteColumnHeader.js
  client/src/components/molecules/pageHeader.js
  client/src/components/organisms/column/index.js
  client/src/components/organisms/column/styles.css
  client/src/components/organisms/header/index.js
  client/src/components/organisms/header/styles.css
  client/src/components/organisms/noteColumn.js
  client/src/components/organisms/noteColumns.js
  client/src/components/pages/home.js
  client/src/components/pages/login.js
  client/src/components/templates/project/index.js
  client/src/components/templates/project/styles.css
  client/src/components/templates/template.css
  client/src/main.js
  client/src/pages/project/controller.js
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  client/src/styles.css
  client/src/utils/element.js
  client/src/utils/event.js
Labels: architecture, frontend, ui

#35 docs: project api의 url을 모두 projects로 변경 & 이벤트를 생성하는 api에 projectId 추가
  docs/api.md
Labels: api, document

#34 bugfix: drag and drop
  client/src/pages/project/view.js
  client/src/utils/dragndrop.js
Labels: bug, frontend, ui

#36 feat: API 함수 구현
  .prettierrc
  server/app.js
  server/bin/www.js
  server/controllers/events.js
  server/controllers/groups.js
  server/controllers/notes.js
  server/controllers/projects.js
  server/controllers/user-project-relations.js
  server/controllers/users.js
  server/models/events.js
  server/models/groups.js
  server/models/index.js
  server/models/model.js
  server/models/notes.js
  server/models/projects.js
  server/models/user-project-relations.js
  server/models/users.js
  server/package-lock.json
  server/package.json
  server/routes/events.js
  server/routes/groups.js
  server/routes/index.js
  server/routes/notes.js
  server/routes/projects.js
  server/routes/user-project-relations.js
  server/routes/users.js
  server/utils/auth.js
  server/utils/helper.js
  server/views/error.pug
  server/views/index.pug
  server/views/layout.pug
Labels: api, backend, database

#43 docs: API 문서 업데이트
  docs/api.md
Labels: api, backend

#45 docs: API 문서 업데이트
  docs/api.md
Labels: api, document

#40 feat: 프론트엔드 API 구현 & 프로젝트 로드, 카드 생성 이벤트 구현하기
  client/src/apis/index.js
  client/src/apis/project.js
  client/src/components/molecules/card/index.js
  client/src/components/organisms/column/index.js
  client/src/components/organisms/column/styles.css
  client/src/components/organisms/eventColumn/index.js
  client/src/components/templates/project/styles.css
  client/src/pages/project/controller.js
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  client/src/styles.css
  client/src/utils/event.js
  client/src/utils/helper.js
  server/controllers/groups.js
  server/controllers/notes.js
  server/models/events.js
Labels: api, frontend, ui

#42 feat: API 함수 수정 및 추가 구현
  server/controllers/groups.js
  server/controllers/notes.js
  server/models/events.js
  server/models/groups.js
  server/models/model.js
  server/models/notes.js
  server/routes/groups.js
  server/routes/notes.js
  server/utils/helper.js
Labels: api, backend

#50 chore: 전체 프로젝트에 prettier 적용
  .prettierrc
  client/banner.js
  client/src/apis/index.js
  client/src/apis/project.js
  client/src/apis/user.js
  client/src/components/atoms/button/styles.css
  client/src/components/atoms/counter/index.js
  client/src/components/atoms/counter/styles.css
  client/src/components/atoms/icon/index.js
  client/src/components/atoms/icon/styles.css
  client/src/components/atoms/input/index.js
  client/src/components/atoms/input/styles.css
  client/src/components/atoms/label/index.js
  client/src/components/atoms/textarea/index.js
  client/src/components/atoms/textarea/styles.css
  client/src/components/molecules/card/index.js
  client/src/components/molecules/card/styles.css
  client/src/components/molecules/header/index.js
  client/src/components/molecules/header/styles.css
  client/src/components/organisms/column/index.js
  client/src/components/organisms/column/styles.css
  client/src/components/organisms/eventColumn/index.js
  client/src/components/organisms/eventColumn/styles.css
  client/src/components/organisms/loginColumn/index.js
  client/src/components/organisms/loginColumn/styles.css
  client/src/components/templates/login/index.js
  client/src/components/templates/login/styles.css
  client/src/components/templates/project/index.js
  client/src/components/templates/project/styles.css
  client/src/index.html
  client/src/main.js
  client/src/pages/login/controller.js
  client/src/pages/login/model.js
  client/src/pages/login/view.js
  client/src/pages/project/controller.js
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  client/src/styles.css
  client/src/utils/dragndrop.js
  client/src/utils/element.js
  client/src/utils/event.js
  client/src/utils/helper.js
  server/controllers/groups.js
  server/controllers/notes.js
  server/controllers/user-project-relations.js
  server/models/events.js
  server/models/index.js
  server/utils/auth.js
Labels: refactor

#52 Feature/47/page scroll
  client/src/components/templates/project/styles.css
Labels: frontend, ui

#53 feat: move event
  .prettierrc
  client/src/apis/index.js
  client/src/apis/project.js
  client/src/components/atoms/input/index.js
  client/src/pages/project/controller.js
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  client/src/utils/dragndrop.js
  client/src/utils/helper.js
  server/models/groups.js
  server/models/notes.js
Labels: api, frontend

#59 feat: Groups, Notes에 대한 액션 구현
  client/dist/index.html
  client/dist/main.css
  client/dist/main.js
  client/src/apis/index.js
  client/src/components/atoms/icon/styles.css
  client/src/components/atoms/input/index.js
  client/src/components/atoms/textarea/index.js
  client/src/components/molecules/card/index.js
  client/src/components/molecules/modal/index.js
  client/src/components/molecules/modal/styles.css
  client/src/components/organisms/column/styles.css
  client/src/components/organisms/eventColumn/index.js
  client/src/components/organisms/eventColumn/styles.css
  client/src/components/organisms/groupColumn/index.js
  client/src/components/organisms/groupColumn/styles.css
  client/src/components/templates/project/index.js
  client/src/components/templates/project/styles.css
  client/src/pages/project/controller.js
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  server/controllers/groups.js
  server/controllers/notes.js
  server/controllers/projects.js
  server/models/notes.js
  server/models/projects.js
  server/utils/helper.js
Labels: frontend, ui

#61 feat: font-awesome 아이콘으로 아이콘 스타일링
  client/dist/index.html
  client/dist/main.css
  client/dist/main.js
  client/src/components/atoms/icon/index.js
  client/src/components/atoms/icon/styles.css
  client/src/components/molecules/card/index.js
  client/src/components/molecules/modal/index.js
  client/src/components/molecules/modal/styles.css
  client/src/components/organisms/eventColumn/index.js
  client/src/components/organisms/groupColumn/index.js
  client/src/components/organisms/groupColumn/styles.css
  client/src/components/templates/create/styles.css
  client/src/components/templates/project/index.js
  client/src/components/templates/project/styles.css
  client/src/index.html
Labels: frontend, ui

#65 hotfix: 데모 때 발견된 버그 해결
  client/dist/index.html
  client/dist/main.css
  client/dist/main.js
  client/src/components/molecules/card/index.js
  client/src/components/molecules/card/styles.css
  client/src/components/molecules/header/styles.css
  client/src/components/organisms/eventColumn/styles.css
  client/src/components/organisms/groupColumn/styles.css
  client/src/components/templates/project/index.js
  client/src/components/templates/project/styles.css
  client/src/pages/project/model.js
  client/src/pages/project/view.js
  client/src/utils/helper.js
  server/controllers/notes.js
  server/models/groups.js
  server/models/projects.js
  server/routes/users.js
Labels: backend, bug, frontend, ui

#67 hotfix: 데모 때 발견된 추가적인 버그 해결
  client/src/components/molecules/card/index.js
  client/src/components/templates/project/styles.css
Labels: bug, frontend, ui

#69 docs: 배포 링크 및 미리보기 추가
  README.md
  docs/images/column-and-event.gif
  docs/images/drag-and-drop.gif
  docs/images/login.gif
Labels: document
